//
// Created by Sergio Marin Sanchez on 23/2/24.
//

#ifndef IMAGE_PROCESSING_EXERCISE_02B_COMPARE_H
#define IMAGE_PROCESSING_EXERCISE_02B_COMPARE_H

#define EQUAL_FILES '1'
#define DIFFERENT_FILES '0'

#endif //IMAGE_PROCESSING_EXERCISE_02B_COMPARE_H
